apiVersion: v1
kind: PersistentVolume
metadata:
 name: elassandra-data
spec:
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteOnce
 storageClassName: slow
 hostPath:
  path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/elassandra